version: '3'

volumes:
  db:
  bundle:

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    tty: true
    stdin_open: true
